language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install pip -U
  - pip install -r requirements.txt
  - pip install codecov==2.0.15 pytest-cov==2.8.1 pytest==5.2.2

script:
  - pytest --cov=. --cov-report term-missing

after_success:
  - codecov